FROM python:3.12-slim

ENV PUID=1000
ENV PGID=1000

RUN apt-get update -y
RUN apt-get install -y libcairo2
RUN apt-get install -y tini
RUN pip install poetry

COPY README.md ./
COPY poetry.lock ./
COPY pyproject.toml ./
COPY src /src

RUN poetry install --no-interaction --no-ansi

WORKDIR /src

#ENTRYPOINT [ "poetry", "run", "python3", "bot.py" ]
ENTRYPOINT ["tini", "--", "poetry", "run", "python3", "-u", "bot.py"]
