services:
  main:
    build: 
      context: .
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3000:8000"
    environment:
      DB_CONNECT_STRING: $DB_CONNECT_STRING
    volumes:
      - ./src/static:/src/static
    image: git.tcrez.dev/tcrez/checkin-viz
