FROM python:3.12-slim

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y sqlite3 libsqlite3-dev

RUN pip install poetry

COPY README.md ./
COPY poetry.lock ./
COPY pyproject.toml ./
COPY scripts/huey /
COPY src/*.py /

RUN poetry install --no-interaction --no-ansi

ENTRYPOINT [ "poetry", "run", "./huey" ]
