name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: pi
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls ${{ gitea.workspace }}
      - name: Build
        run: |
          VERSION_NUMBER="$(date -u +%Y-%m-%dT%H:%M:%SZ)|$(git rev-parse --short HEAD)" docker compose build
      - name: Push
        run: docker compose push
      - name: Update container
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WT_TOKEN }}" "https://wt.tcrez.dev/v1/update"
